---
extends: default

rules:
  line-length:
    max: 160
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    level: warning
  brackets:
    min-spaces-inside: 1
    max-spaces-inside: 1
    level: warning
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
    level: warning
...
