---
- name: Install prometheus node_exporter
  ansible.builtin.include_tasks: install.yaml
  tags:
    - prometheus
    - node_exporter

- name: UFW | open access to node_exporter
  ansible.builtin.include_tasks: ufw.yaml
  when: enable_ufw | bool
  tags:
    - prometheus
    - node_exporter
    - ufw

- name: Web Auth | Deploy web.yml
  ansible.builtin.copy:
    dest: "{{ prometheus_node_exporter_config_path }}/web.yml"
    content: |
      {% if prometheus_node_exporter_web_auth.enable | d(false) | bool %}
      basic_auth_users:
        {{ prometheus_node_exporter_web_auth.user }}: {{ prometheus_node_exporter_web_auth.password | password_hash('bcrypt', '1234567890123456789012') }}
      {% endif %}
    owner: "{{ prometheus_node_exporter_user }}"
    group: "{{ prometheus_node_exporter_group }}"
    mode: '0640'
  notify: Restart node_exporter
  tags:
    - prometheus
    - node_exporter
    - config
...
